api_platform:
    title: MyHealth API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            apiKey:
                name: 'Authorization'
                type: 'header'
